jobs:
    build-linux-aarch64:
        machine:
            image: ubuntu-2204:2023.07.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-aarch64 -f Dockerfile-aarch64 .
            - run: docker run -v $(realpath ./):/mnt/src build-linux-aarch64
            - run: mkdir -p ./artifacts/
            - run: sudo mv target/aarch64-unknown-linux-gnu/release/minit ./artifacts/minit-aarch64
            - persist_to_workspace:
                root: ./artifacts
                paths:
                    - minit-aarch64
    build-linux-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-x86-64 -f Dockerfile-x86_64 .
            - run: docker run -v $(realpath ./):/mnt/src build-linux-x86-64
            - run: mkdir -p ./artifacts/
            - run: sudo mv target/x86_64-unknown-linux-gnu/release/minit ./artifacts/minit-x86_64
            - persist_to_workspace:
                root: ./artifacts
                paths:
                    - minit-x86_64
    publish-github-release:
        docker:
            - image: rust:latest
        steps:
            - checkout
            - attach_workspace:
                at: ./artifacts
            - run: 
                command: |
                    GHR_VERSION=0.13.0
                    GHR_URL=https://github.com/tcnksm/ghr/releases/download/v0.13.0/ghr_v0.13.0_linux_amd64.tar.gz
                    wget "$GHR_URL" && tar xzf ghr_v${GHR_VERSION}_linux_amd64.tar.gz && mv ghr_v${GHR_VERSION}_linux_amd64/ghr /usr/bin/ghr && rm -r ghr_v${GHR_VERSION}_linux_amd64.tar.gz ghr_v${GHR_VERSION}_linux_amd64/
            - run:
                command: |
                    VERSION=$(cargo read-manifest | grep -Po '"version":.*?[^\\]",' | grep -Po '[\d\.]+')
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
                name: Publish Release on GitHub
version: 2.1
workflows:
    build-crossplatform:
        jobs:
            - build-linux-aarch64
            - build-linux-x86_64
            - publish-github-release:
                context: Github
                requires:
                    - build-linux-aarch64
                    - build-linux-x86_64

