jobs:
    build-linux-aarch64:
        machine:
            image: ubuntu-2204:2023.07.1
            resource_class: arm.medium
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-aarch64 -f Dockerfile-aarch64 .
            - run: docker run -v $(realpath ./):/mnt/src build-linux-aarch64
            - store_artifacts:
                destination: minit-aarch64
                path: target/aarch64-unknown-linux-gnu/release/minit
    build-linux-x86_64:
        machine:
            image: ubuntu-2204:2024.05.1
        steps:
            - checkout
            - run: git submodule sync
            - run: git submodule update --init
            - run: docker build -t build-linux-x86-64 -f Dockerfile-x86_64 .
            - run: docker run -v $(realpath ./):/mnt/src build-linux-x86-64
            - store_artifacts:
                destination: minit-x86_64
                path: target/x86_64-unknown-linux-gnu/release/minit
    publish-github-release:
        docker:
            - image: cibuilds/github:0.10
        steps:
            - attach_workspace:
                at: ./artifacts
            - run:
                command: |
                    VERSION=0.1.0
                    echo ${GITHUB_TOKEN}
                    echo ${CIRCLE_PROJECT_USERNAME}
                    echo ${CIRCLE_PROJECT_REPONAME}
                    echo ${CIRCLE_SHA1}
                    echo ${VERSION}
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${VERSION} ./artifacts/
                name: Publish Release on GitHub
version: 2.1
workflows:
    build-crossplatform:
        jobs:
            - build-linux-aarch64
            - build-linux-x86_64
            - publish-github-release:
                context: Github
                requires:
                    - build-linux-aarch64
                    - build-linux-x86_64

